name: KomodoGDX

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15
          architecture: x64
      
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      
      - name: Build Core
        run: ./gradlew core:build
      
      - name: Build Desktop example
        run: ./gradlew desktop:build
      
      - name: Build Editor
        run: ./gradlew editor:build
      
      - name: Build Editor executable
        run: ./gradlew editor:installDist
      
      - uses: actions/upload-artifact@v2
        with:
          name: Editor Application
          path: editor/build/install/editor
